from enum import Enum

class ForestCentreSpecies(Enum):
    PINE = 1
    SPRUCE = 2
    SILVER_BIRCH = 3
    DOWNY_BIRCH = 4
    ASPEN = 5
    GREY_ALDER = 6
    COMMON_ALDER = 7
    OTHER_CONIFEROUS_SPECIES = 8
    OTHER_DECIDUOUS_SPECIES = 9
    DOUGLAS_FIR = 10
    JUNIPER = 11
    SHORE_PINE = 12
    EUROPEAN_WHITE_ELM = 13
    LARCH = 14
    SMALL_LEAVED_LIME = 15
    BLACK_SPRUCE = 16
    WILLOW = 17
    MOUNTAIN_ASH = 18
    ABIES = 19
    GOAT_WILLOW = 20
    COMMON_ASH = 21
    KEDAR = 22
    SERBIAN_SPRUCE = 23
    OAK = 24
    BIRD_CHERRY = 25
    MAPLE = 26
    CURLY_BIRCH = 27
    WYCH_ELM = 28