from enum import Enum

class VMISpecies(Enum):
    PINE = 1
    SPRUCE = 2
    SILVER_BIRCH = 3
    DOWNY_BIRCH = 4
    ASPEN = 5
    GREY_ALDER = 6
    COMMON_ALDER = 7
    MOUNTAIN_ASH = 8
    GOAT_WILLOW = 9
    OTHER_CONIFEROUS_SPECIES = 10
    SHORE_PINE = 11
    KEDAR = 12
    OTHER_PINE = 13
    LARCH = 14
    ABIES = 15
    OTHER_SPRUCE = 16
    THUJA = 17
    JUNIPER = 18
    YEW = 19
    OTHER_DECIDUOUS_SPECIES = 20
    BAY_WILLOW = 21
    EUROPEAN_WHITE_ELM = 22
    WYCH_ELM = 23
    SMALL_LEAVED_LIME = 24
    POPLAR = 25
    COMMON_ASH = 26
    OAK = 27
    BIRD_CHERRY = 28
    MAPLE = 29
    HAZEL = 30