from forestdatamodel.enums.forest_centre import ForestCentreSpecies
from forestdatamodel.enums.vmi import VMISpecies
from forestdatamodel.enums.mela import MelaTreeSpecies
from forestdatamodel.enums.internal import InternalTreeSpecies

fc_to_internal = {
    ForestCentreSpecies.PINE: InternalTreeSpecies.PINE,
    ForestCentreSpecies.SPRUCE: InternalTreeSpecies.SPRUCE,
    ForestCentreSpecies.SILVER_BIRCH: InternalTreeSpecies.SILVER_BIRCH,
    ForestCentreSpecies.DOWNY_BIRCH: InternalTreeSpecies.DOWNY_BIRCH,
    ForestCentreSpecies.ASPEN: InternalTreeSpecies.ASPEN,
    ForestCentreSpecies.GREY_ALDER: InternalTreeSpecies.GREY_ALDER,
    ForestCentreSpecies.COMMON_ALDER: InternalTreeSpecies.COMMON_ALDER,
    ForestCentreSpecies.OTHER_CONIFEROUS_SPECIES: InternalTreeSpecies.OTHER_CONIFEROUS,
    ForestCentreSpecies.OTHER_DECIDUOUS_SPECIES: InternalTreeSpecies.OTHER_DECIDUOUS,
    ForestCentreSpecies.DOUGLAS_FIR: InternalTreeSpecies.DOUGLAS_FIR,
    ForestCentreSpecies.JUNIPER: InternalTreeSpecies.JUNIPER,
    ForestCentreSpecies.SHORE_PINE: InternalTreeSpecies.SHORE_PINE,
    ForestCentreSpecies.EUROPEAN_WHITE_ELM: InternalTreeSpecies.EUROPEAN_WHITE_ELM,
    ForestCentreSpecies.LARCH: InternalTreeSpecies.LARCH,
    ForestCentreSpecies.SMALL_LEAVED_LIME: InternalTreeSpecies.SMALL_LEAVED_LIME,
    ForestCentreSpecies.BLACK_SPRUCE: InternalTreeSpecies.BLACK_SPRUCE,
    ForestCentreSpecies.WILLOW: InternalTreeSpecies.WILLOW,
    ForestCentreSpecies.MOUNTAIN_ASH: InternalTreeSpecies.MOUNTAIN_ASH,
    ForestCentreSpecies.ABIES: InternalTreeSpecies.ABIES,
    ForestCentreSpecies.GOAT_WILLOW: InternalTreeSpecies.GOAT_WILLOW,
    ForestCentreSpecies.COMMON_ASH: InternalTreeSpecies.COMMON_ASH,
    ForestCentreSpecies.KEDAR: InternalTreeSpecies.KEDAR,
    ForestCentreSpecies.SERBIAN_SPRUCE: InternalTreeSpecies.SERBIAN_SPRUCE,
    ForestCentreSpecies.OAK: InternalTreeSpecies.OAK,
    ForestCentreSpecies.BIRD_CHERRY: InternalTreeSpecies.BIRD_CHERRY,
    ForestCentreSpecies.MAPLE: InternalTreeSpecies.MAPLE,
    ForestCentreSpecies.CURLY_BIRCH: InternalTreeSpecies.CURLY_BIRCH,
    ForestCentreSpecies.WYCH_ELM: InternalTreeSpecies.WYCH_ELM,
    ForestCentreSpecies.UNKNOWN_CONIFEROUS_SPECIES: InternalTreeSpecies.UNKNOWN_CONIFEROUS,
    ForestCentreSpecies.UNKNOWN_DECIDUOUS_SPECIES: InternalTreeSpecies.UNKNOWN_DECIDUOUS,
}

vmi_to_internal = {
    VMISpecies.PINE: InternalTreeSpecies.PINE,
    VMISpecies.SPRUCE: InternalTreeSpecies.SPRUCE,
    VMISpecies.SILVER_BIRCH: InternalTreeSpecies.SILVER_BIRCH,
    VMISpecies.DOWNY_BIRCH: InternalTreeSpecies.DOWNY_BIRCH,
    VMISpecies.ASPEN: InternalTreeSpecies.ASPEN,
    VMISpecies.GREY_ALDER: InternalTreeSpecies.GREY_ALDER,
    VMISpecies.COMMON_ALDER: InternalTreeSpecies.COMMON_ALDER,
    VMISpecies.MOUNTAIN_ASH: InternalTreeSpecies.MOUNTAIN_ASH,
    VMISpecies.GOAT_WILLOW: InternalTreeSpecies.GOAT_WILLOW,
    VMISpecies.OTHER_CONIFEROUS_SPECIES: InternalTreeSpecies.OTHER_CONIFEROUS,
    VMISpecies.SHORE_PINE: InternalTreeSpecies.SHORE_PINE,
    VMISpecies.KEDAR: InternalTreeSpecies.KEDAR,
    VMISpecies.OTHER_PINE: InternalTreeSpecies.OTHER_PINE,
    VMISpecies.LARCH: InternalTreeSpecies.LARCH,
    VMISpecies.ABIES: InternalTreeSpecies.ABIES,
    VMISpecies.OTHER_SPRUCE: InternalTreeSpecies.OTHER_SPRUCE,
    VMISpecies.THUJA: InternalTreeSpecies.THUJA,
    VMISpecies.JUNIPER: InternalTreeSpecies.JUNIPER,
    VMISpecies.YEW: InternalTreeSpecies.YEW,
    VMISpecies.OTHER_DECIDUOUS_SPECIES: InternalTreeSpecies.OTHER_DECIDUOUS,
    VMISpecies.BAY_WILLOW: InternalTreeSpecies.BAY_WILLOW,
    VMISpecies.EUROPEAN_WHITE_ELM: InternalTreeSpecies.EUROPEAN_WHITE_ELM,
    VMISpecies.WYCH_ELM: InternalTreeSpecies.WYCH_ELM,
    VMISpecies.SMALL_LEAVED_LIME: InternalTreeSpecies.SMALL_LEAVED_LIME,
    VMISpecies.POPLAR: InternalTreeSpecies.POPLAR,
    VMISpecies.COMMON_ASH: InternalTreeSpecies.COMMON_ASH,
    VMISpecies.OAK: InternalTreeSpecies.OAK,
    VMISpecies.BIRD_CHERRY: InternalTreeSpecies.BIRD_CHERRY,
    VMISpecies.MAPLE: InternalTreeSpecies.MAPLE,
    VMISpecies.HAZEL: InternalTreeSpecies.HAZEL,
}
